Repository Icinga/icingaweb2-module-x509, pull requests merged in 2022-09, with the labels that each got.

#115 icingacli x509 check host: correct (previously inverted) thresholds
  application/clicommands/CheckCommand.php
Labels: bug, cla/signed

#72 Fix openssl verify command for older OpenSSL versions
  library/X509/CertificateUtils.php
Labels: bug, cla/signed

#85 Support PostgreSQL
  application/clicommands/CheckCommand.php
  application/controllers/CertificatesController.php
  application/controllers/ChainController.php
  application/controllers/UsageController.php
  doc/02-Installation.md
  etc/schema/postgresql.schema.sql
  library/X509/CertificateDetails.php
  library/X509/CertificateUtils.php
  library/X509/Controller.php
  library/X509/DbTool.php
  library/X509/Job.php
  library/X509/ProvidedHook/HostsImportSource.php
  library/X509/ProvidedHook/ServicesImportSource.php
  library/X509/SqlFilter.php
  library/X509/UsageTable.php
Labels: enhancement, cla/signed

#117 icingacli x509 check: take the whole chain into account
  application/clicommands/CheckCommand.php
Labels: bug, cla/signed

#113 Fix integer overflow and log total IPs to be scanned within a CIDR
  library/X509/Job.php
Labels: bug, cla/signed

#119 x509ImportSource#getDb(): SET SESSION SQL_MODE as in the other getDb()s
  library/X509/ProvidedHook/x509ImportSource.php
Labels: cla/signed

#121 UsageController: Allow filtering & sorting by port
  application/controllers/UsageController.php
Labels: enhancement, cla/signed

#124 Introduce `Database` trait
  application/clicommands/JobsCommand.php
  application/clicommands/ScanCommand.php
  library/X509/Command.php
  library/X509/Common/Database.php
  library/X509/Controller.php
  library/X509/Job.php
  library/X509/ProvidedHook/X509ImportSource.php
Labels: enhancement, cla/signed

#126 Database: Fix calling to undefined method `$this->Config()`
  library/X509/Common/Database.php
Labels: bug, cla/signed

#127 Fix access to DB data with incorrect fetch mode
  library/X509/CertificateUtils.php
  library/X509/Job.php
Labels: bug, cla/signed
