Repository Icinga/icingaweb2-module-x509, pull requests merged in 2023-02, with the labels that each got.

#129 Make use of ipl/orm
  application/clicommands/CheckCommand.php
  application/clicommands/ImportCommand.php
  application/controllers/CertificateController.php
  application/controllers/CertificatesController.php
  application/controllers/ChainController.php
  application/controllers/DashboardController.php
  application/controllers/UsageController.php
  application/views/scripts/certificates/index.phtml
  application/views/scripts/usage/index.phtml
  etc/schema/postgresql.schema.sql
  library/X509/CertificateDetails.php
  library/X509/CertificateUtils.php
  library/X509/CertificatesTable.php
  library/X509/ChainDetails.php
  library/X509/Controller.php
  library/X509/DataTable.php
  library/X509/Job.php
  library/X509/Model/Behavior/DERBase64.php
  library/X509/Model/Behavior/ExpressionInjector.php
  library/X509/Model/Behavior/Ip.php
  library/X509/Model/X509Certificate.php
  library/X509/Model/X509CertificateChain.php
  library/X509/Model/X509CertificateChainLink.php
  library/X509/Model/X509CertificateSubjectAltName.php
  library/X509/Model/X509Dn.php
  library/X509/Model/X509JobRun.php
  library/X509/Model/X509Target.php
  library/X509/ProvidedHook/HostsImportSource.php
  library/X509/ProvidedHook/ServicesImportSource.php
  library/X509/ProvidedHook/X509ImportSource.php
  library/X509/SqlFilter.php
  library/X509/UsageTable.php
  library/X509/Web/Control/SearchBar/ObjectSuggestions.php
  phpcs.xml
Labels: enhancement, cla/signed

#130 Prefer object access over array access
  application/clicommands/CheckCommand.php
  application/controllers/CertificatesController.php
  application/controllers/DashboardController.php
  application/controllers/UsageController.php
  library/X509/CertificateDetails.php
  library/X509/CertificatesTable.php
  library/X509/ChainDetails.php
  library/X509/DataTable.php
  library/X509/UsageTable.php
Labels: enhancement, cla/signed

#138 Change all `timestamp` columns to `bigint` & adjust all usages
  application/clicommands/CheckCommand.php
  application/clicommands/ImportCommand.php
  application/controllers/CertificatesController.php
  application/controllers/DashboardController.php
  application/controllers/UsageController.php
  doc/80-Upgrading.md
  etc/schema/mysql-upgrade/v1.2.0.sql
  etc/schema/mysql.schema.sql
  etc/schema/postgresql.schema.sql
  library/X509/CertificateDetails.php
  library/X509/CertificateUtils.php
  library/X509/Controller.php
  library/X509/ExpirationWidget.php
  library/X509/Job.php
  library/X509/Model/X509Certificate.php
  library/X509/Model/X509CertificateChain.php
  library/X509/Model/X509CertificateChainLink.php
  library/X509/Model/X509CertificateSubjectAltName.php
  library/X509/Model/X509Dn.php
  library/X509/Model/X509JobRun.php
  library/X509/Model/X509Target.php
Labels: enhancement, cla/signed

#131 Successive scans
  application/clicommands/RescanCommand.php
  application/clicommands/ScanCommand.php
  library/X509/Common/ScanUtils.php
  library/X509/Job.php
  library/X509/Model/X509Target.php
Labels: enhancement, cla/signed

#147 Donut: Optimize donut contrast for dark/light mode
  library/X509/Donut.php
  public/css/module.less
Labels: enhancement, cla/signed

#149 CSS: Fix cert color var usage
  public/css/module.less
Labels: bug, cla/signed

#151 README.md: Change required PHP version badge
  README.md
Labels: cla/signed

#150 Fix scanning
  etc/schema/mysql-upgrade/v1.2.0.sql
  library/X509/Job.php
Labels: bug, cla/signed

#152 Remove `Controller::getDb()` override
  library/X509/Common/Database.php
  library/X509/Controller.php
Labels: enhancement, cla/signed

#154 Don't call `inet_ntop()` on already transformed `IP`
  library/X509/UsageTable.php
Labels: bug, cla/signed

#155 Job: Ensure to render hostname with no value filter as `IS NULL`
  library/X509/Job.php
Labels: bug, cla/signed
