Repository Icinga/icingaweb2-module-x509, pull requests merged in 2023-04, with the labels that each got.

#159 Adjust schema path
  doc/02-Installation.md
  doc/80-Upgrading.md
  schema/mysql-upgrades/1.0.0.sql
  schema/mysql-upgrades/1.1.0.sql
  schema/mysql-upgrades/1.2.0.sql
  schema/mysql.schema.sql
  schema/pgsql.schema.sql
Labels: enhancement, cla/signed

#164 ChainDetails: Add a context when translating `Subject`
  library/X509/ChainDetails.php
Labels: cla/signed

#163 Job: Don't exclude `net` & `broadcast` addr
  library/X509/Job.php
Labels: bug

#156 doc: Replace `certs`, `usages` & `dashboard` overview screenshots
  doc/res/x509-certificates.png
  doc/res/x509-dashboard.png
  doc/res/x509-usage.png
Labels: enhancement, cla/signed

#165 Fix order of IP behaviours
  library/X509/Job.php
  library/X509/Model/X509Target.php
Labels: bug, cla/signed

#122 Provide job schedules widget
  application/clicommands/JobsCommand.php
  application/controllers/JobsController.php
  application/forms/Config/JobConfigForm.php
  library/X509/JobsIniRepository.php
  public/css/module.less
Labels: enhancement, cla/signed

#158 Release/v1.2.0
  .gitignore
  .mailmap
  AUTHORS
  module.info
Labels: cla/signed

#167 Ip: Extend binary behaviour
  library/X509/Model/Behavior/Ip.php
  library/X509/Model/X509Target.php
Labels: bug, cla/signed

#168 Recommend to install from packages
  doc/02-Installation.md
  doc/02-Installation.md.d/From-Source.md
  doc/80-Upgrading.md
Labels: cla/signed

#170 Fix `CheckCommand`
  application/clicommands/CheckCommand.php
Labels: bug, cla/signed
