Repository Icinga/icingaweb2-module-x509, pull requests merged in 2023-09, with the labels that each got.

#202 Use `Style` element to create dynamic inline styles
  library/X509/ExpirationWidget.php
  public/css/module.less
Labels: enhancement, cla/signed

#205 ExpirationWidget: Cast progress ratio to string float correctly
  library/X509/ExpirationWidget.php
Labels: bug, cla/signed

#186 Github Actions: Add Phpstan
  .github/workflows/php.yml
  application/clicommands/CheckCommand.php
  application/controllers/CertificateController.php
  application/controllers/ChainController.php
  application/controllers/JobsController.php
  library/X509/CertificateUtils.php
  library/X509/Common/JobUtils.php
  library/X509/Controller.php
  library/X509/Hook/SniHook.php
  library/X509/Job.php
  library/X509/ProvidedHook/HostsImportSource.php
  library/X509/ProvidedHook/ServicesImportSource.php
  library/X509/SortAdapter.php
  library/X509/Web/Control/SearchBar/ObjectSuggestions.php
  phpstan-baseline.neon
  phpstan.neon
Labels: enhancement, cla/signed

#204 CertificateUtils: Split also unknow cert alt names correctly
  library/X509/CertificateUtils.php
Labels: bug, cla/signed

#206 Use `StyleWithNonce` element
  library/X509/ExpirationWidget.php
Labels: cla/signed

#194 Separate jobs and schedule config
  application/clicommands/JobsCommand.php
  application/clicommands/ScanCommand.php
  application/controllers/JobController.php
  application/controllers/JobsController.php
  application/forms/Config/JobConfigForm.php
  application/forms/Jobs/JobConfigForm.php
  application/forms/Jobs/ScheduleForm.php
  configuration.php
  doc/03-Configuration.md
  doc/04-Scanning.md
  doc/res/weekly-schedules.png
  library/X509/Common/JobOptions.php
  library/X509/Common/JobUtils.php
  library/X509/Common/Links.php
  library/X509/Job.php
  library/X509/JobsIniRepository.php
  library/X509/Model/Behavior/DERBase64.php
  library/X509/Model/Behavior/ExpressionInjector.php
  library/X509/Model/Behavior/Ip.php
  library/X509/Model/X509Certificate.php
  library/X509/Model/X509CertificateChain.php
  library/X509/Model/X509CertificateChainLink.php
  library/X509/Model/X509CertificateSubjectAltName.php
  library/X509/Model/X509Dn.php
  library/X509/Model/X509Job.php
  library/X509/Model/X509JobRun.php
  library/X509/Model/X509Schedule.php
  library/X509/Model/X509Target.php
  library/X509/Schedule.php
  library/X509/Widget/JobDetails.php
  library/X509/Widget/Jobs.php
  library/X509/Widget/Schedules.php
  phpstan-baseline.neon
  phpstan.neon
  public/css/module.less
  schema/mysql-upgrades/1.3.0.sql
  schema/mysql.schema.sql
  schema/pgsql-upgrades/1.3.0.sql
  schema/pgsql.schema.sql
Labels: enhancement, cla/signed

#198 Integrate unit tests
  .github/workflows/php.yml
  phpunit.xml
  test/php/Lib/TestModel.php
  test/php/library/X509/Common/JobUtilsTest.php
  test/php/library/X509/JobTest.php
  test/php/library/X509/Model/Behavior/DERBase64Test.php
  test/php/library/X509/Model/Behavior/ExpressionInjectorTest.php
  test/php/library/X509/Model/Behavior/IpTest.php
Labels: enhancement, cla/signed

#195 Provide migration hook & migrate jobs config to database
  application/clicommands/MigrateCommand.php
  doc/80-Upgrading.md
  library/X509/Model/Schema.php
  library/X509/ProvidedHook/DbMigration.php
  run.php
  schema/mysql-upgrades/1.3.0.sql
  schema/mysql.schema.sql
  schema/pgsql-upgrades/1.3.0.sql
  schema/pgsql.schema.sql
Labels: enhancement, cla/signed

#209 Drop obsolete `jobs` view scripts
  application/views/scripts/jobs/index.phtml
Labels: cla/signed

#208 docs: Add missing grants in MYSQL manual setup
  doc/02-Installation.md
Labels: bug, cla/signed
