Repository Icinga/icingaweb2-module-x509, pull requests merged in 2023-11, with the labels that each got.

#220 don't reinitialize variable on iteration
  application/clicommands/JobsCommand.php
Labels: bug, cla/signed

#222 Do not clone jobs
  application/clicommands/JobsCommand.php
  library/X509/Job.php
Labels: bug, cla/signed

#223 Make `Database` trait a singleton
  application/clicommands/CheckCommand.php
  application/clicommands/CleanupCommand.php
  application/clicommands/ImportCommand.php
  application/clicommands/JobsCommand.php
  application/clicommands/MigrateCommand.php
  application/clicommands/ScanCommand.php
  application/clicommands/VerifyCommand.php
  application/controllers/CertificateController.php
  application/controllers/CertificatesController.php
  application/controllers/ChainController.php
  application/controllers/DashboardController.php
  application/controllers/JobController.php
  application/controllers/JobsController.php
  application/controllers/UsageController.php
  application/forms/Jobs/JobConfigForm.php
  application/forms/Jobs/ScheduleForm.php
  library/X509/Command.php
  library/X509/Common/Database.php
  library/X509/Controller.php
  library/X509/Job.php
  library/X509/ProvidedHook/DbMigration.php
  library/X509/ProvidedHook/HostsImportSource.php
  library/X509/ProvidedHook/ServicesImportSource.php
  library/X509/ProvidedHook/X509ImportSource.php
  library/X509/Web/Control/SearchBar/ObjectSuggestions.php
Labels: bug, cla/signed

#224 Document x509 daemon
  doc/03-Configuration.md
Labels: bug, cla/signed, area/documentation

#225 Document cleanup command
  application/clicommands/CleanupCommand.php
  doc/11-Housekeeping.md
  phpstan-baseline.neon
Labels: enhancement, cla/signed

#226 Run phpstan for all supported PHP versions
  .github/workflows/php.yml
  phpstan-baseline-7x.neon
  phpstan-baseline-8x.neon
  phpstan-baseline-by-php-version.php
  phpstan-baseline-common.neon
  phpstan.neon
Labels: enhancement, cla/signed

#227 workflows: Add PHP 8.3
  .github/workflows/php.yml
  application/controllers/UsageController.php
  phpstan-baseline-common.neon
Labels: cla/signed

#228 Raise module version to `1.3.2`
  module.info
Labels: cla/signed
